<nav>
  <ul>
    <li><a href="index.php">Home</a></li>
    <li><a href="jobs.php">Jobs</a></li>
    <li><a href="apply.php">Application</a></li>
    <li><a href="about.php">About</a></li>
    <li><a href="mailto:krex1179@gmail.com">Email</a></li>
    <li><a href="manage.php">Manager</a></li>
    <li><a href="register.php">Register</a></li>
    <li><a href="enhancements.php">Enhancement</a></li>
  </ul>
</nav> 